services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_service
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db_service
      - DB_PORT=5432
    networks:
      - django_network

  db_service:
    image: postgis/postgis:16-master
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - MAX_CLIENT_CONN=200
    ports:
      - "${DB_PORT}:5432"
    networks:
      - django_network
volumes:
  postgres_data:

networks:
  django_network:
    # external: true