# Generated by Django 4.2.29 on 2026-03-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalities',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
